### ISSUE TITLE
Add DN parsing

### ISSUE THREAD

**Issue by bluecmd** [vanackere/ldap#3]
Would you be interested in accepting a PR for a DN parsing lib?

DN parsing is a bit complicated (RFC 4515) and as far as I can tell there are no Go libraries to do this. I need this functionality in a project that uses this LDAP library and I feel like implementing it in the upstream product would be a waste if other people can also benefit from my work.

Let me know if you would welcome such a contribution.

**Comment by vanackere** [comment]
Hi,

 Yes, it looks like a useful feature and I'd welcome such a contribution. You should also note that go ldap development is now quite active again at https://github.com/go-ldap/ldap (most changes from my fork were integrated there), so perhaps you should also/instead send a pull request there ?

**Comment by bluecmd** [comment]
Sounds good! Thanks.

**Comment by bluecmd** [comment]
FYI; https://github.com/go-ldap/ldap/pull/19
